# Generated by Django 2.1.2 on 2019-05-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190506_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_html',
            field=models.TextField(blank=True, editable=False, verbose_name='正文 html 代码 '),
        ),
    ]
